### PR TITLE
Propose new parking lot

### PR DESCRIPTION
**Pull request by emontantes**

### CODE REVIEW

**Comment by emontantes** [comment]
created index, new & create with redirects. Still working on getting correct params and will add in the pundit to authorize create/delete with current_user.

Create form is running
still need to work on delete form.

**Comment by Camvillard** [comment]
thanks Esteban ! Can you work on the params before we merge ?

**Comment by emontantes** [comment]
calendar date tab was added without css, currently working on a way to get it to show with Victor

**Comment by emontantes** [comment]
Gems Added

**Pull request merged**
